config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'search' => 'static_pages#search'
  get 'stats'  => 'static_pages#stats'
  get 'about'  => 'static_pages#about'
  get 'rules'  => 'static_pages#intro'
  get 'intro'  => 'static_pages#intro'
  get 'changelog' => 'static_pages#changelog'
  get 'stream' => 'static_pages#stream'
  get 'advice' => 'static_pages#advice'
  get 'api_docs' => 'static_pages#api_docs'

  get 'guides/crispy_doom' => 'guides#crispy_doom'
  get 'guides/prboom_plus' => 'guides#dsda_doom'
  get 'guides/dsda_doom' => 'guides#dsda_doom'

  get 'record_timeline'      => 'wads#record_timeline'
  get 'record_timeline_json' => 'wads#record_timeline_json'
  get 'compare_movies'      => 'wads#compare_movies'
  get 'compare_movies_json' => 'wads#compare_movies_json'

  get 'feed'         => 'demos#feed'
  get 'demos/:id/hidden_tag' => 'demos#hidden_tag'

  post  'api/demos/'        => "demos#api_create"
  patch 'api/demos/'        => "demos#api_update"
  delete 'api/demos/'       => "demos#api_delete"
  post  'api/wads'          => "wads#api_create"
  patch 'api/wads/:id'      => "wads#api_update"
  post  'api/players/'      => "players#api_create"
  patch 'api/players/:id'   => "players#api_update"
  post  'api/merge_players' => "players#api_merge"
  post  'api/ports/'        => "ports#api_create"
  post  'api/tokens/'       => "tokens#api_create"
  post  'api/otp/'          => "otp#reset"

  get 'api/demos' => 'demos#api_demos'
  get 'api/demos/records' => 'demos#api_records'
  get 'api/demos/:id' => 'demos#api_get'
  get 'api/wads/:id' => 'wads#api_get'
  get 'api/players' => 'players#api_players'
  get 'api/players/:id' => 'players#api_get'

  get 'no_file' => "static_pages#no_file"

  resources :players, only: [:show, :index] do
    get :autocomplete_player_username, :on => :collection
  end
  get 'players/:id/stats' => 'players#stats', as: 'player_stats'
  get 'players/:id/record_view' => 'players#record_view', as: 'player_record_view'
  get 'players/:id/history' => 'players#history', as: 'player_history'

  resources :iwads, only: [:show, :index]
  get 'iwads/:id/stats' => 'iwads#stats', as: 'iwad_stats'

  resources :wads, only: [:show, :index]
  get 'wads/:id/stats' => 'wads#stats', as: 'wad_stats'
  get 'wads/:id/table_view' => 'wads#table_view', as: 'wad_table_view'
  get 'wads/:id/leaderboard' => 'wads#leaderboard', as: 'wad_leaderboard'
  get 'wads/:id/history' => 'wads#history', as: 'wad_history'

  resources :ports, only: [:index], :id => /([^\/])+/ do
    get :autocomplete_port_family, :on => :collection
  end

  post 'cookies/accept', to: 'cookies#accept', as: 'cookies_accept'
  post 'cookies/theme', to: 'cookies#theme', as: 'cookies_theme'

  match '*unmatched', to: 'static_pages#not_found', via: :all
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  RECORD_INDEX_LIMIT = 50

  def home
  end

  def stats
    @record_index_players =
      Domain::Player.list(by_record_index: true, page: 1, per: RECORD_INDEX_LIMIT)
  end

  def about
  end

  def search
    @search = params[:search]
    @iwads = Domain::Iwad.search(term: @search)
    @players = Domain::Player.search(term: @search)
    @wads = Domain::Wad.search(term: @search)

    if @iwads.count == 1 && @players.count == 0 && @wads.count == 0
      redirect_to iwad_url(@iwads.first)
    elsif @players.count == 1 && @iwads.count == 0 && @wads.count == 0
      redirect_to player_url(@players.first)
    elsif @wads.count == 1 && @iwads.count == 0 && @players.count == 0
      redirect_to wad_url(@wads.first)
    end
  end

  def no_file
  end

  def intro
  end

  def changelog
  end

  def stream
  end

  def advice
  end

  def api_docs
  end

  def not_found
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def get_docs()
    [
      { # GET /api/demos
        endpoint: 'GET /api/demos',
        description: 'This is the main endpoint to query demo lists. It can be used to get all demos from a wad for displaying tables, or getting the feed by sorting by last id.<br>
                      It doesnt crosslist the record, so you are better off using /api/demos/records if you just need the record of a certain category (for example Doom2 Map01 UV will give you a list without any record, since the first place is in the Pacifist category).',
        parameters: [
          { name: 'wad', required: false, type: 'string', description: "The wad's short name" },
          { name: 'level', required: false, type: 'string', description: "The level name" },
          { name: 'category', required: false, type: 'string', description: "The category name" },
          { name: 'only_records', required: false, type: 'bool', description: "Whether to only list demos that are records (default = <code>false</code>)" },
          { name: 'sort_by', required: false, type: 'string', description: "The field to sort the list by and in what direction.<br> The allowed fields are <code>id</code>, <code>time</code> and <code>date</code>. The direction can be <code>asc</code> or <code>desc</code>. (default = <code>time:asc</code>)" },
          { name: 'page', required: false, type: 'integer', description: "The page number (default = <code>1</code>)" },
          { name: 'per', required: false, type: 'integer', description: "How many demos to show per page (default = <code>50</code>, max = <code>200</code>)" }
        ],
        example_request: 'https://dsdarchive.com/api/demos?wad=plutonia&only_records=true&sort_by=date:asc&page=4',
        example_response: <<~JSON
        {
          "demos": [
            {
              "id": 65897,
              "players": [
                "aconfusedhuman"
              ],
              "time": "1:32.94",
              "category": "NM 100S",
              "level": "Map 08",
              "wad": "plutonia",
              "engine": "DSDA-Doom v0.19.7cl4",
              "date": "2021-09-12T23:28:06.000Z",
              "upload_date": "2021-09-12T23:28:06.000Z",
              "tic_record": true,
              "undisputed_record": false,
              "second_barrier": false,
              "tas": false,
              "guys": 1,
              "suspect": false,
              "cheated": false,
              "notes": [],
              "file": "http://dsdarchive.com/files/demos/plutonia/55364/pl08ns132.zip",
              "video_url": "https://www.youtube.com/watch?v=C16SKN69pWU"
            },

            ...
          ],
          "page": 4,
          "per": 50,
          "total_pages": 7,
          "total_demos": 335
        }
        JSON
      },
      { # GET /api/demos/{id}
        endpoint: 'GET /api/demos/{id}',
        description: 'Returns a specific demo details.',
        parameters: [
          { name: 'id', required: true, type: 'integer', description: "The demo's id" },
        ],
        example_request: 'https://dsdarchive.com/api/demos/68170',
        example_response: <<~JSON
        {
          "id": 68170,
          "players": [
            "almostmatt1"
          ],
          "time": "0:07.74",
          "category": "Other",
          "level": "E1M1",
          "wad": "doom",
          "engine": "XDRE v2.22a",
          "date": "2021-11-02T01:30:44.000Z",
          "upload_date": "2021-11-02T01:30:44.000Z",
          "tic_record": false,
          "undisputed_record": false,
          "second_barrier": false,
          "tas": true,
          "guys": 1,
          "suspect": false,
          "cheated": false,
          "notes": [
            "Nomo. Uses player 3 starting position."
          ],
          "file": "http://dsdarchive.com/files/demos/doom/57604/e1m1ox774.zip",
          "video_url": null
        }
        JSON
      },
      { # GET /api/demos/records
        endpoint: 'GET /api/demos/records',
        description: 'Returns the record demo for a specific run (crosslisted).',
        parameters: [
          { name: 'wad', required: true, type: 'string', description: "The wad's short name" },
          { name: 'level', required: true, type: 'string', description: "The level name" },
          { name: 'category', required: true, type: 'string', description: "The category name" }
        ],
        example_request: 'https://dsdarchive.com/api/demos/records?wad=doom2&level=Map+01&category=UV+Speed',
        example_response: <<~JSON
        {
          "player": "4shockblast",
          "time": "0:04.97",
          "category": "Pacifist",
          "level": "Map 01",
          "wad": "doom2",
          "engine": "DSDA-Doom v0.27.5cl2",
          "date": "2024-04-06T03:46:50.000Z",
          "notes": ["Also Reality"],
          "file": "http://dsdarchive.com/files/demos/doom2/88132/pa01-497.zip"
        }
        JSON
      },
      { # GET /api/players
        endpoint: 'GET /api/players',
        description: 'Returns an alphabetical list of players.',
        parameters: [
          { name: 'page', required: false, type: 'integer', description: "The page number (default = <code>1</code>)" },
          { name: 'per', required: false, type: 'integer', description: "How many players to show per page (default = <code>50</code>, max = <code>200</code>)" }
        ],
        example_request: 'https://dsdarchive.com/api/players?page=4&per=200',
        example_response: <<~JSON
        {
          "players": [
            {
              "username": "kyle_mcawesome",
              "name": "Kyle McAwesome",
              "stats": {
                "demo_count": 1644,
                "total_demo_time": "54:11:18.29",
              }
            },

            ...
          ],
          "page": 4,
          "per": 200,
          "total_pages": 7,
          "total_players": 1294
        }
        JSON
      },
      { # GET /api/players/{username}
        endpoint: 'GET /api/players/{username}',
        description: 'Returns a specific players details',
        parameters: [
          { name: 'username', required: true, type: 'string', description: "The player's short and URL friendly username" },
        ],
        example_request: 'https://dsdarchive.com/api/players/xit_vono',
        example_response: <<~JSON
        {
          "username": "xit_vono",
          "name": "Xit Vono",
          "stats": {
            "demo_count": 1740,
            "total_demo_time": "153:39:19.78",
          }
        }
        JSON
      },
      { # GET /api/wads/{short_name}
        endpoint: 'GET /api/wads/{short_name}',
        description: 'Returns a specific wad details.',
        parameters: [
          { name: 'short_name', required: true, type: 'string', description: "The wad's short name" },
        ],
        example_request: 'https://dsdarchive.com/api/wads/gd',
        example_response: <<~JSON
        {
          "short_name": "gd",
          "name": "Going Down",
          "author": "mouldy",
          "iwad": "doom2",
          "file": "https://dsdarchive.com/files/wads/doom2/1472/gd.zip"
        }
        JSON
      }
    ]
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<% provide(:description, 'A brief history of the demo archive, from 2000 until now') %>

<h1>History</h1>
<hr>
The DSDA first formed out of Opulent's personal demos page,
as written in the oldest news post therein, dated September 2000:
<div class="well well-sm">
  	Page opens; updated my Individual demos page to this page.
  	Again, I encourage anyone to submit a demo. -- I know that the average
  	skill level of these demos is pretty high, but since I know I won't get
  	many takers, don't be afraid to send me a demo. It can be of you on your
  	level on skill 2 using Jdoom. I do have preferences(see info page), but
  	overall.anything goes.  I am starting this page with the release of
  	Doomworld's 10 sectors contest in hope that that will encourage more demo
  	activity.  Expect some hurriedly recorded 10 sectors demos from me shortly.
  	Demos are the best way to show off a level, so start recording...
</div>

The first submission to the archive was a 34 demo Hell Revealed pack by Ryback
in October 2000.  Opulent wrote an
<a href="http://www.doomworld.com/10years/demos/demos01.php">article</a> in
December 2003 on the history of doom demo recording, including this passage
about his inspiration for the archive:
<div class="well well-sm">
  Andy Olivera is one of the most accomplished people in the DOOM community.
  His all-in-one site was the first to be a review site, have his own demos,
  and make his own levels.  All with a quality that you'd think he was dedicated
  to only one of them; as well as being during a time when almost no other
  established sites were having regular updates.  Besides his own demos, he was
  the administrater of the Wad Master's Competition, a pwad contest done at
  regular intervals.  His site provided the root of the content and the main
  inspiration for the DOOMed Speed Demos Archive.  Besides Yonatan, Andy was
  the most influencial person in pwad single-player demos ever.
  <br>...<br>
  The DOOMed Speed Demos Archive(DSDA).  A cheap knockoff(I like to think of it
  as a tribute ;) of the Quake Speed Demos Archive, the DSDA is home to a very
  large collection of demos for third-party maps.   The first major site to
  allow demos recorded with source ports, it was started in August 2000 by me
  and allows demos of virtually any type of recording.
</div>

Andy Olivera introduced the second incarnation of the site in November 2008,
as detailed in his first news post:
<div class="well well-sm">
  Greetings DooMers! Andy Olivera here. It's been a long time coming, but the
  new, improved DooMed Speed Demos Archive is finally here.
  <br><br>
  Some background: This redesign was born approximately two years ago when
  Opulent was feeling down. It occured to me that having all those demos
  piling up would make the updating process a daunting task: updating each of
  the over 900 WAD pages individually, moving the files to their proper
  locations, keeping the tables up to date with entries from the dormant(dead?)
  Compet-N. I came to the conclusion that the DSDA had grown too large for
  manual updating and a new approach was needed. Whether this new approach
  would be utilized by Opulent, myself or someone else, I didn't know. So, with
  my meager coding knowledge I set out to redesign the DSDA as a dynamic,
  database-generated website. I had no idea it would take so long!
  <br><br>
  The backend portion took around six months. My first instinct was to use
  phpMyAdmin, but for the amount of records I needed to enter, it was just too
  slow and bloated. The initial plan was to write a simple record entry script.
  Thankfully, as I was writing and learning a bit more about PHP, it evolved
  into an efficient system of record management and file handling. That
  evolution probably saved me from getting burned out and abandoning the project
  during the next step.
  <br><br>
  Next up was the task of entering all the existing demos into the database.
  This took nearly 18 months and was incredibly tedious. Third, and finally,
  came the designing of the actual website. This step was a picnic compared to
  the other two. Though it did contain a few hurdles and the site didn't arrive
  with all the superfluous features I'd planned, I'm satisfied with the way it's
  turned out and I think you will be, too.
  <br>...<br>
  And finally, in closing this inaugural update I think it important to salute
  the man who created all this in the first place. Doug "Opulent" Merrill kept
  the DSDA running smoothly for almost seven years. That's the longest any DooM
  demo site operator has managed to hang on. A glance at the site statistics
  above should give you an idea as to just how much work this entailed and the
  level of dedication required. So if you're a demo-lover as well, drop him an
  eMail and thank him for his years of service.
</div>

In 2016, we began to consider building a new DSDA from scratch, with
a much broader scope (adding Heretic and Hexen) and more ambitious goals.
Work officially began at the start of 2017, and this became the primary archive
in 2019.
<br>
<hr>

<h3>Team</h3>
<ul>
  <li>Kraflab</li>
  <li>Zero-Master</li>
  <li>4shockblast</li>
  <li>GarrettChan</li>
  <li>Keyboard_Doomer</li>
  <li>paymentplan</li>
  <li>PBeGood</li>
  <li>Arsinikk</li>
</ul>

<strong>Special Thanks</strong>: Opulent, Andy Olivera, eLim, PVS, veovis, Coincident, Depr4vity, TheLoneliness and everyone in the community

app/views/static_pages/advice.html.erb
<% provide(:title, 'New Player Advice') %>
<% provide(:description, 'Advice for players new to Doom speedrunning') %>

<h2>Advice for new players</h2>

<h3>Running Doom & Doom 2 (IWADs)</h3>

<p>
  As a new runner, it may seem obvious to start with Doom 1, Episode 1.
  However, this episode is quite demanding and frustrating (not just for new
  runners).
  There is a lot of luck involved, due to unavoidable damage from zombiemen.
  That luck is mitigated by better movement: the more you play, the less luck
  you'll need.
  This relationship between skill and luck makes Episode 1 particularly
  inefficient if you are trying to improve at the game.
  You won't be getting as much "real" experience.
  If you're bent on starting with something from the original games,
  Doom 1, Episode 2 is a good option.
  This run has some cool tricks that will get you into speedrunning the game,
  but is much less demanding and not as punishing.
</p>

<p>
  Doom 2 is a highly technical run.
  To mimic the WR is nigh impossible for a new player, because there is
  a huge cataloge of knowledge required to get through it.
  Furthermore, the rule above applies: the less skilled you are,
  the more luck you need to survive.
  You could use an old route, but you'll have difficulty finding
  resources to help you learn it.
  That being said, if you are into learning a lot of tricks and willing to
  grind, this can still be a rewarding endeavor!
</p>

<p>
  <strong>
    The most important thing is to pick something you enjoy,
    and that will motivate you to keep improving!
  </strong>
  Feel free to take any approach that works for you, and ask for help in the
  discord. We are happy to assist you in your journey!
</p>

<h3>Improving Movement</h3>

<p>
  Improving your movement has a ripple effect of making everything easier.
  It boils down to a simple principle: the less time you spend in any area,
  the less damage you'll take from hitscans (unavoidable gunshots).
  A little time invested early on can save you a ton of time in your efforts.
</p>

<p>
  Doom happens to have a special commandline parameter, <code>-nomonsters</code>,
  which allows you to play the game without enemies.
  The use of this parameter is actually quite common in doom speedrunning,
  to the point where we have an official category for this,
  and some of the most impressive runs have come out of it.
  The positive benefit of investing time in this category can't be understated.
</p>

<p>
  A common suggestion is to play Doom 2 Map 31 NoMo (normal exit)
  and try to get in the 31-33s range.
  This run is relatively "simple" but will get you comfortable with sr40 / sr50
  and with movement around doors, which is not as trivial as it sounds.
  The current record (as of writing this) is 28.91 by Looper.
  Check out the run and see what time you can get.
  Most importantly, feel free to ask in the discord for a critique if you aren't
  sure what you're missing to get a faster time.
</p>

<h3>Running Custom Maps (PWADs)</h3>

<p>
  It might surprise you to know that the vast majority of Doom speedrunning
  activity happens on custom maps. The community of mappers is incredibly
  active to this day, and the maps offer new and exciting challenges that
  attract both casual players and speedrunners.
</p>

<p>
  Since the pool of maps outpaces the number of runners, PWADs offer you the
  opportunity to route something new, or to compete against players that
  are closer to your skill level (when compared with more optimized IWAD maps).
  The variety of gameplay also means you can work on a lot of different skills,
  which will help you a lot as you progress.
</p>

<p>
  For some players this is more satisfying than competing against IWAD records,
  but what works best is something for you to find out.
  If you want any suggestions on PWADs to try out, or runs to look into,
  just ask in the discord.
</p>

<h3>Running ILs</h3>

<p>
  While running full episodes or full games has a certain appeal, it can be
  counter-productive when you are starting off.
  It can be a good idea to pick levels / runs that you enjoy and working on them
  instead.
  This also will give you a shorter "optimization cycle", where you can
  improve a run quickly and move onto the next thing
  (or stay and grind out something special).
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% provide(:description, 'Archive and leaderboards for classic Doom, Heretic, and Hexen speedrunning') %>

<%= render 'layouts/wad_list' %>

<div class="jumbotron">
  <div class="container">
    <h2>Doom Speed Demo Archive</h2>
    <p>
      The home of classic Doom speedrunning.
      This site archives demos created for Doom and related games
      (Heretic, Hexen, etc).  <%= link_to('Ports', ports_path) %> has a list of allowed ports,
      although care should be taken to use the intended environment for each
      WAD.  Post your demos to the
      <a href="https://www.doomworld.com/forum/37-doom-speed-demos/">Speed Demo Forum</a>
      on DoomWorld.
    </p>
    <p>
      New? Check out the <%= link_to('Intro', intro_path) %> for general rules and useful information.
      Also see the <%= link_to('Advice', advice_path) %> page for recommendations on how to improve
      when starting out. Ready to start recording? Check out the recommended source port for doom speedrunning:
      <a href="https://github.com/kraflab/dsda-doom">DSDA-Doom</a>.
    </p>
    <% cache "home_v002:#{last_update}" do %>
      <h4>
        Proudly hosting <%= Demo.count %> demos, by <%= Player.count %> players, for
        <%= Wad.count %> wads, with a total time of
        <%= Service::Tics::ToString.call(Demo.all.sum(:tics), with_cs: false) %>
      </h4>
    <% end %>
  </div>
</div>

<% cache "home_active_v002:#{last_update}" do %>
  <% day_range = 90 %>
  <br>
  <div class="hidden-overflow">
    <div class="center-text col-md-6">
      <div class="panel panel-default panel-modest">
        <div class="panel-heading">
          <h3 class="panel-title">Active Wads (last <%= day_range %> days)</h3>
        </div>
        <div class="table-wrapper">
          <table class="table">
            <% active_wads(day_range).each do |wad_id, count| %>
              <%= active_wad_entry(Wad.find(wad_id), count) %>
            <% end %>
          </table>
        </div>
      </div>
    </div>
    <div class="center-text col-md-6">
      <div class="panel panel-default panel-modest">
        <div class="panel-heading">
          <h3 class="panel-title">Active Players (last <%= day_range %> days)</h3>
        </div>
        <div class="table-wrapper">
          <table class="table">
            <% active_players(day_range).each do |player_id, count| %>
              <%= active_player_entry(Player.find(player_id), count) %>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
  <br>
<% end %>

<%= render 'layouts/categories' %>
<%= render 'layouts/info' %>

app/views/static_pages/no_file.html.erb
<% provide(:title, 'No File') %>
<% provide(:description, 'The page for missing files') %>

<h3>There is no file associated with this object.</h3>

<h4>This could be because it is a commercial product, or otherwise not available.</h4>

app/views/static_pages/not_found.html.erb
<% provide(:title, '404') %>
<% provide(:description, 'Page not found') %>

<div class="center-text">
  <h1>Oh no, the demons ate the page!</h1>
  <span class="error-404">
    4
    <%= image_tag "pinky.gif", alt: "Pinky", class: "error-image"%>
    4
  </span>

  <h3>That's what happens when you are here looking at demos instead of recording some.</h3>
  <h3>The <%= link_to("stream's", stream_url) %> kill counter isn't going to increase by itself.</h3>
</div>

app/views/static_pages/search.html.erb
<% provide(:title, 'Search') %>
<% provide(:description, 'Simple search for players and WADs') %>

<h3>"<%= @search %>" search results:</h3>

<% if @iwads.count > 0 %>
  <div>
    <button class="toggle-search-results" data-toggle="collapse" data-target="#iwad_results" aria-expanded="true" aria-controls="iwad_results">
      <span class="glyphicon glyphicon-chevron-down"></span> Iwad results (<%= @iwads.count %>):
    </button>
    <div id="iwad_results" class="collapse in">
      <% @iwads.each do |iwad| %>
        <li>
          <%= link_to "#{iwad.name} (#{iwad.short_name})", wad_path(iwad) %>
        </li>
      <% end %>
    </div>
  </div>
  <br>
<% end %>

<% if @players.count > 0 %>
  <div>
    <button class="toggle-search-results" data-toggle="collapse" data-target="#player_results" aria-expanded="true" aria-controls="player_results">
      <span class="glyphicon glyphicon-chevron-down"></span> Player results (<%= @players.count %>):
    </button>
    <div id="player_results" class="collapse in">
      <% @players.each do |player| %>
        <li>
          <%= link_to "#{player.name} (#{player.username})", player_path(player) %>
        </li>
      <% end %>
    </div>
  </div>
  <br>
<% end %>

<% if @wads.count > 0 %>
  <div>
    <button class="toggle-search-results" data-toggle="collapse" data-target="#wad_results" aria-expanded="true" aria-controls="wad_results">
      <span class="glyphicon glyphicon-chevron-down"></span> Wad results (<%= @wads.count %>):
    </button>
    <div id="wad_results" class="collapse in">
      <% @wads.each do |wad| %>
        <li>
          <%= link_to "#{wad.name} (#{wad.short_name})", wad_path(wad) %>
        </li>
      <% end %>
    </div>
  </div>
  <br>
<% end %>

app/views/static_pages/stats.html.erb
<% provide(:title, 'Stats') %>
<% provide(:description, "Detailed stats for the archive as a whole") %>

<% cache [:stats_v002, last_update] do %>
  <% time_sum = Demo.all.sum(:tics) %>
  <% demo_count = Demo.count %>
  <% player_count = Player.count %>
  <% wad_count = Wad.count %>

<div class="center-text">
  <div class="page-header">
    <h1>
      Stats & Charts
    </h1>
  </div>
  <div class="panel panel-default panel-modest left-text">
    <div class="table-wrapper">
      <table class="table table-striped table-modest">
        <div class="panel-heading">
          <h3 class="panel-title center-text">Stats & Charts</h3>
        </div>
        <tbody>
          <tr>
            <td>Number of demos</td>
            <td><%= demo_count %></td>
          </tr>
          <tr>
            <td>Number of players</td>
            <td><%= player_count %></td>
          </tr>
          <tr>
            <td>Number of wads</td>
            <td><%= wad_count %></td>
          </tr>
          <tr>
            <td>Total demo time</td>
            <td><%= Service::Tics::ToString.call(time_sum, with_cs: false) %> </td>
          </tr>
          <tr>
            <td>Average demos per player</td>
            <td><%= demo_count / player_count %></td>
          </tr>
          <tr>
            <td>Average demos per wad</td>
            <td><%= demo_count/ wad_count %></td>
          </tr>
          <tr>
            <td>Average demo time</td>
            <td><%= Service::Tics::ToString.call(time_sum / demo_count, with_cs: false) %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <br>
</div>

<% end %>

<hr>
<div class="center-text">
  <h3>Record Index Top 50</h3>
  <p>The Record Index is the number of demos beaten by record runs.</p>
  <div class="panel panel-default panel-modest left-text">
    <div class="table-wrapper">
      <table class="table table-striped table-modest">
        <thead>
          <tr>
            <th>#</th>
            <th>Player</th>
            <th>Record Index</th>
          </tr>
        </thead>
        <tbody>
          <% @record_index_players.each_with_index do |player, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%= link_to player.name, player_path(player) %></td>
              <td><%= player.record_index %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div id="demo_count_by_year" class="chart-style">
  <%= column_chart Domain::Demo.demo_count_by_year,
  title: 'Demo Count by Year (Estimated)',
  dataset: default_bar_plot_options,
  library: default_plot_options,
  nonce: content_security_policy_script_nonce,
  id: 'demo_count_by_year', html: '' %>
</div>

app/views/static_pages/stream.html.erb
<% provide(:title, 'Stream') %>
<% provide(:description, '24/7 stream showcasing records from across the history of Doom speedrunning') %>

<div class="center-text">
    <h1>Doom Speed Demos Stream (by Zero-Master)</h1>
    <hr>
</div>

<div id="twitch-embed"></div>

<script src="https://embed.twitch.tv/embed/v1.js"></script>