config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'search' => 'static_pages#search'
  get 'stats'  => 'static_pages#stats'
  get 'about'  => 'static_pages#about'
  get 'rules'  => 'static_pages#intro'
  get 'intro'  => 'static_pages#intro'
  get 'changelog' => 'static_pages#changelog'
  get 'stream' => 'static_pages#stream'
  get 'advice' => 'static_pages#advice'
  get 'api_docs' => 'static_pages#api_docs'

  get 'guides/crispy_doom' => 'guides#crispy_doom'
  get 'guides/prboom_plus' => 'guides#dsda_doom'
  get 'guides/dsda_doom' => 'guides#dsda_doom'

  get 'record_timeline'      => 'wads#record_timeline'
  get 'record_timeline_json' => 'wads#record_timeline_json'
  get 'compare_movies'      => 'wads#compare_movies'
  get 'compare_movies_json' => 'wads#compare_movies_json'

  get 'feed'         => 'demos#feed'
  get 'demos/:id/hidden_tag' => 'demos#hidden_tag'

  post  'api/demos/'        => "demos#api_create"
  patch 'api/demos/'        => "demos#api_update"
  delete 'api/demos/'       => "demos#api_delete"
  post  'api/wads'          => "wads#api_create"
  patch 'api/wads/:id'      => "wads#api_update"
  post  'api/players/'      => "players#api_create"
  patch 'api/players/:id'   => "players#api_update"
  post  'api/merge_players' => "players#api_merge"
  post  'api/ports/'        => "ports#api_create"
  post  'api/tokens/'       => "tokens#api_create"
  post  'api/otp/'          => "otp#reset"

  get 'api/demos' => 'demos#api_demos'
  get 'api/demos/records' => 'demos#api_records'
  get 'api/demos/:id' => 'demos#api_get'
  get 'api/wads/:id' => 'wads#api_get'
  get 'api/players' => 'players#api_players'
  get 'api/players/:id' => 'players#api_get'

  get 'no_file' => "static_pages#no_file"

  resources :players, only: [:show, :index] do
    get :autocomplete_player_username, :on => :collection
  end
  get 'players/:id/stats' => 'players#stats', as: 'player_stats'
  get 'players/:id/record_view' => 'players#record_view', as: 'player_record_view'
  get 'players/:id/history' => 'players#history', as: 'player_history'

  resources :iwads, only: [:show, :index]
  get 'iwads/:id/stats' => 'iwads#stats', as: 'iwad_stats'

  resources :wads, only: [:show, :index]
  get 'wads/:id/stats' => 'wads#stats', as: 'wad_stats'
  get 'wads/:id/table_view' => 'wads#table_view', as: 'wad_table_view'
  get 'wads/:id/leaderboard' => 'wads#leaderboard', as: 'wad_leaderboard'
  get 'wads/:id/history' => 'wads#history', as: 'wad_history'

  resources :ports, only: [:index], :id => /([^\/])+/ do
    get :autocomplete_port_family, :on => :collection
  end

  post 'cookies/accept', to: 'cookies#accept', as: 'cookies_accept'
  post 'cookies/theme', to: 'cookies#theme', as: 'cookies_theme'

  match '*unmatched', to: 'static_pages#not_found', via: :all
end

app/views/layouts/_categories.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Demo Categories & Types</h3>
  </div>
  <div class="panel-body">
    <p>
      The following categories and types are the most common and widely
      recognized, but this archive will host any demo.
    </p>
    <br>

    <div class="table-wrapper">
      <table class="table">
        <thead>
          <tr>
            <th>Category</th>
            <th>File Code</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="cell-no-wrap">UV Speed</td>
            <td>-</td>
            <td>Exit as fast as possible on skill 4.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">UV Max</td>
            <td>m</td>
            <td>Exit with all monsters dead (except lost souls) and all secrets collected on skill 4.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">UV Fast</td>
            <td>f</td>
            <td>Exit with all monsters dead (except lost souls) and all secrets collected on skill 4, using the -fast parameter.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">UV Respawn</td>
            <td>r</td>
            <td>Exit with 100% Kills and all secrets collected on skill 4, using the -respawn parameter.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">UV Tyson</td>
            <td>t</td>
            <td>Exit with all monsters dead (except lost souls) on skill 4, using only weapons 1 and 2 (fist, chainsaw, pistol).</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">Pacifist</td>
            <td>p</td>
            <td>Exit as fast as possible on skill 4, without hurting monsters either directly or indirectly (no barrels).</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">NM Speed</td>
            <td>n</td>
            <td>Exit as fast as possible on skill 5.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">NM 100S</td>
            <td>s</td>
            <td>Exit with all secrets collected on skill 5.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">NoMo</td>
            <td>o</td>
            <td>Exit as fast as possible, using the -nomonsters parameter.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">NoMo 100S</td>
            <td>os</td>
            <td>Exit with all secrets collected, using the -nomonsters parameter.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">Stroller</td>
            <td>str</td>
            <td>Pacifist, using the -turbo 50 parameter, without strafing. -stroller if the port supports it.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">Collector</td>
            <td>col</td>
            <td>
              Exit with all weapons & keys picked up, using the -nomonsters parameter.
              Legacy category, we are no longer accepting submissions.
            </td>
          </tr>
          <tr>
            <td class="cell-no-wrap">Other</td>
            <td></td>
            <td>Any nonstandard demo category / challenge.</td>
          </tr>
        </tbody>
      </table>
    </div>
    <br>
    <div class="table-wrapper">
      <table class="table">
        <thead>
          <tr>
            <th>Type</th>
            <th>File Code</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="cell-no-wrap">TAS</td>
            <td>x</td>
            <td>Any category, using tool assistance.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">Coop</td>
            <td>c</td>
            <td>Any category, with some friends.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">Reality</td>
            <td>reality</td>
            <td>Any category, without taking damage.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">Coop Spawns</td>
            <td>cspwn</td>
            <td>Any category, using the -coop_spawns parameter.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">Solo Net</td>
            <td>sn</td>
            <td>Any category, using the -solo-net parameter.</td>
          </tr>
          <tr>
            <td class="cell-no-wrap">Turbo</td>
            <td>tu</td>
            <td>Any category, using the -turbo xyz parameter.</td>
          </tr>
        </tbody>
      </table>
    </div>
    <br>
  </div>
</div>

app/views/layouts/_cookies.html.erb
<% if cookies[:accept] != 'true' %>
  <div class=" cookie-banner">
    This website uses cookies strictly to save your chosen theme and any other view user preferences.
    <%= button_to 'Accept', cookies_accept_path(), method: :post, class: "btn" %>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div class="center-text">
  <%= flash_messages(flash) %>
</div>

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
  <small>
    <p class="pull-left"> © <%= Time.now.year %></p>
    <p class="pull-left">&nbsp;|&nbsp;</p>
    <div class="btn-group p-short">
      <button class='dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
        Theme
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <% themes.each do |theme| %>
          <li class=<%= @current_theme == theme.downcase ? 'dropdown-selected' : nil %>>
            <%= link_to theme, cookies_theme_path(theme: theme), method: :post, class: "theme-dropdown-item unstyled-button" %>
          </li>
        <% end %>
      </ul>
    </div>

    <a class="pull-right" href="<%= about_url %>">About</a>
    <p class="pull-right">&nbsp;|&nbsp;</p>
    <a class="pull-right" href="<%= changelog_url %>">Changelog</a>
    <p class="pull-right">&nbsp;|&nbsp;</p>
    <a class="pull-right" href="<%= api_docs_url %>">API</a>
    <br>
  </small>
</footer>
<hr>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url %>">DSDA</a>
    </div>
    <div id="header-navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <a href="<%= players_url %>">Players</a>
        </li>
        <li>
          <a href="<%= iwads_url %>">Iwads</a>
        </li>
        <li>
          <a href="<%= ports_url %>">Ports</a>
        </li>
      </ul>
      <%= bootstrap_form_tag url: search_path, method: "get", layout: :inline,
                            html: { class: "navbar-form navbar-left" } do |f| %>
        <%= f.text_field :search, placeholder: "Search", hide_label: true, control_class: "form-control" %>
        <%= f.submit "Search", class: "btn btn-default" %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="<%= stream_url %>">Stream</a>
        </li>
        <li>
          <a href="<%= feed_url %>">Feed</a>
        </li>
        <li>
          <a href="<%= stats_url %>">Stats</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_info.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Recording & Playback</h3>
  </div>
  <div class="panel-body">
    <p>
      For demo recording and playback information, check the detailed
      <a href=https://www.doomworld.com/forum/topic/130670-welcome-to-the-speed-demos-forum-getting-started-port-usage-info-co-op-etc/>
        welcome thread
      </a>
      at the Speed Demo Forum.  The majority of players prefer to use DSDA-Doom to
      record and play demos for vanilla, limit-removing, mbf, and boom formats.
      (G)ZDoom is generally only used for (G)ZDoom-specific wads.  Note that
      DSDA-Doom maintains backwards compatibility, but <b>(G)ZDoom does not</b>.
      Always use the source port version that a (G)ZDoom demo was recorded on to
      ensure proper playback.
    </p>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_wad_list.html.erb
<div class="navbar">
  <ul class="nav navbar-nav wad-list">
    <li class="wad-letter">
      <%= link_to 'WADs', wads_url, class: 'wads-brand' %>
    </li>
    <% ( ['#'] + ('A'..'Z').to_a).each do |char| %>
      <li class="wad-letter">
        <% letter = char == '#' ? '9' : char.downcase %>
        <%= link_to char, wads_url(letter: letter) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= yield(:description) %>">
    <% if 0 %>
      <%= stylesheet_link_tag "themes/#{@current_theme}", media: 'all'%>
    <% end %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  </head>
  <body>
    <div class="bg-image"></div>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
      <%= render 'layouts/cookies' %>
      <%= render 'layouts/footer' %>
      <%= debug(params.to_unsafe_h) if Rails.env.development? %>
    </div>
  </body>
</html>